[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
RAILWAY_STATIC_URL = "true"
NODE_ENV = "production"

[environments.production.variables]
# Environment variables will be set in Railway dashboard
# MONGODB_URI = "your-mongodb-connection-string"
# PORT = "3000"
